- name: demo on the play level variable
  hosts: all
  vars:
    URL: jayadeep.example.com
  tasks:
  - name: print URL
    ansible.builtin.debug:
      msg: URL - {{ URL }}


- name: demo on the task level variable
  hosts: all
  tasks:
  - name: print URL
    ansible.builtin.debug:
      msg: URL - {{ URL }}
    vars:
      URL: task.example.com


- name: demo vars from a file
  hosts: all
  vars_files:
    jayadeepvars.yml
  tasks:
    - name: print vars from file
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: demo for the roles
  hosts: all
  roles:
    - jayadeep